### PR TITLE
feat: add standard MFE i18n

### PR DESCRIPTION
**Pull request by OmarIthawi**
## Changes
 - Support for react-intl FormattedMessage
 - Prepare for openedx-translations
 - Installed `npm install --legacy-peer-deps @edx/frontend-platform@4.2.0` since `entrprise-utils` is stuck on `4.0.1` but both packages are compatible for the purposes for `frontend-admin-portal`. Unfrotantely upgrading the frontend-platform `peerDependency` to the latest `frontend-platform` slipped through review in the PR: https://github.com/openedx/frontend-enterprise/pull/306 
 - Move all i18n imports into `src/i18n/index.js` so `intl-imports.js` can override it with latest translations
 - Add `atlas` into `make pull_translations` when `OPENEDX_ATLAS_PULL` environment variable is set.

### Node regarding `frontend-platform-shim` package
This is a transitional package that should be removed once the `frontend-app-admin-portal` is fully upgraded to frontend-platform@4.1.x+ version and using node.js v18.

Once the upgrade is completed, the `frontend-platform-shim` package will _intentionally fail_ to install due to `peerDepedency`. This failure means the following should be done:

 - The shim package is no longer required and should be removed.
 - The admin portal Makefile should use the standard `intl_imports` path e.g. https://github.com/openedx/frontend-app-learning/blob/a78496a3f67c16edf5e022f7cb0d44faa227ba6e/Makefile#L4

## TODO

- [x] Add intl provider
- [x] Bump up the frontend-platform version first: https://github.com/openedx/frontend-app-admin-portal/pull/983:
    - **Blocked** by entrprise-utils platform upgrade: https://github.com/openedx/frontend-enterprise/pull/306
- [x] Bump the frontend-platform one more time: https://github.com/openedx/frontend-enterprise/pull/329
 - [x] Fix tests and lint rules
 - [x] Test pulled translations
 - [x] Quick QA for translated content: <details><summary>Screenshot (look at the footer)</summary><kbd>image</kbd></details> 

## For all changes

- [x] Ensure adequate tests are in place (or reviewed existing tests cover changes)

## Component changes (might affect visuals)

- [x] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

References
----------

This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Check the links above for full information about the overall project.

Internalization is being rearchitected in Open edX Python, XBlock, Micro-frontend, and other projects. There are a number of immediately visible changes:
 - Remove source and language translations from the repositories, hence no `.json`, `.po` or `.mo` files will be committed into the repos.
 - Add standardized `make extract_translations` in all repositories
 - Push user-facing messages strings into [openedx/openedx-translations](https://github.com/openedx/openedx-translations/).
 - Integrate root repositories with [openedx/openedx-atlas](https://github.com/openedx/openedx-atlas/) to pull translations on build/deploy time

Breaking Changes
----------------

One of the primary goals of the project is to **avoid breaking changes**. If you noticed any suspicious code, please raise your concern.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by brian-smith-tcril** [comment]
I see the spreadsheet notes this repo as needing the temp package, and https://github.com/openedx/frontend-app-admin-portal/pull/983 has been closed as too costly. I'm marking this PR as blocked by other work for now.

**Comment by OmarIthawi** [comment]
> I see the spreadsheet notes this repo as needing the temp package, and #983 has been closed as too costly. I'm marking this PR as blocked by other work for now.

Yup, it's blocked by the enterprise frontend upgrade PR: https://github.com/openedx/frontend-enterprise/pull/306

**Comment by OmarIthawi** [comment]
This is not blocked anymore, and the npm dependency issue is resolved.

I need to test it and add screenshots.

**Comment by OmarIthawi** [comment]
@brian-smith-tcril this is ready for review.

**Comment by OmarIthawi** [comment]
@mphilbrick211 please note that this PR is ready for review and no longer `waiting for author`.

**Review by brian-smith-tcril — APPROVED** [review]
This is great! Thank you so much for this!

**Pull request merged**
