### PR TITLE
FC-0001: Replace usages enterprise_catalog Enterprise API V1

### PR DESCRIPTION
**Pull request by ruzniaievdm**
(2 of 5) for closes https://github.com/openedx/public-engineering/issues/61
## Description:

Replace this [usage](https://github.com/openedx/frontend-app-admin-portal/blob/master/src/data/services/LmsApiService.js#L254-L256) with corresponding to the **enterprise-catalog** service

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ruzniaievdm! I've created [OSPR-6795](https://openedx.atlassian.net/browse/OSPR-6795) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by feanil — APPROVED** [review]
This change looks good to me, @adamstankiewicz can you take a second look and help get this deployed?

**Comment by feanil** [comment]
@natabene this is ready for 2U review.

**Comment by openedx-webhooks** [comment]
@ruzniaievdm 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-admin-portal&entry.867055334=https://github.com/openedx/frontend-app-admin-portal/pull/801&entry.1484655318=https://github.com/ruzniaievdm&entry.752974735=2022-06-13+15:53&entry.1917517419=2022-09-19+16:37&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
